name: Deploy config server
on: push
jobs:
  Change-Server-Config:
    runs-on: ubuntu-latest
    steps:
      - name: clone code to runner
        uses: actions/checkout@v3
      - name: List files in the repository and tar.gz directory
        run: |
          cd ${{ github.workspace }} && cd ..
          ls -la
          tar -czvf artifact.tar.gz server
          mv artifact.tar.gz ${{ github.workspace }}
          cd ${{ github.workspace }}
          ls -la

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "${{ github.workspace }}/artifact.tar.gz"
          target: "/home/ubuntu"

      - name: use the upload artifact github action
        uses: actions/upload-artifact@v3
        with:
          name: My artifact
          path: "${{ github.workspace }}/artifact.tar.gz"

      - name: nginx modified
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/github/workspace
            tar -xzvf artifact.tar.gz
            cd /home/ubuntu/github/workspace/server/nginx
            sudo rsync -av . /etc/nginx/
            sudo chown root. -R /etc/nginx/
            sudo nginx -t
            sudo service nginx restart

      - name: PHP-FPM modified
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/github/workspace/server/php-fpm
            sudo rsync -av . /etc/php/7.4/fpm
            sudo chown root. -R /etc/php/7.4/fpm
            sudo service php7.4-fpm restart

      - name: forward artifact to Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            echo "${{ secrets.KEY }}" | tr -d '\r' | ssh-add -
            ssh ${{ secrets.USERNAME }}@10.0.0.5 -T "mkdir -p /home/ubuntu/github/workspace"
            scp /home/ubuntu/github/workspace/artifact.tar.gz ${{ secrets.USERNAME }}@10.0.0.5:/home/ubuntu/github/workspace
            ssh ${{ secrets.USERNAME }}@10.0.0.5 -T "cd /home/ubuntu/github/workspace && tar -xzvf artifact.tar.gz"

      - name: mysql modified
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            echo "${{ secrets.KEY }}" | tr -d '\r' | ssh-add -
            ssh ${{ secrets.USERNAME }}@10.0.0.5 -T "cd /home/ubuntu/github/workspace/server/mysql \
            && sudo rsync -av . /etc/mysql/ \
            && sudo chown root. -R /etc/mysql/ \
            && sudo service mysql restart"

      - name: redis modified
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            echo "${{ secrets.KEY }}" | tr -d '\r' | ssh-add -
            ssh ${{ secrets.USERNAME }}@10.0.0.5 -T "cd /home/ubuntu/github/workspace/server/redis \
            && sudo rsync -av . /etc/redis/ \
            && sudo chown redis. -R /etc/redis/* \
            && sudo service redis restart"      
            