name: Deploy config server
on: push
jobs:
  Change-Server-Config:
    runs-on: ubuntu-latest
    steps:
      - name: clone code to runner
        uses: actions/checkout@v3
      - name: List files in the repository and tar.gz directory
        run: |
          cd ${{ github.workspace }} && cd ..
          ls -la
          tar -czvf artifact.tar.gz server
          mv artifact.tar.gz ${{ github.workspace }}
          cd ${{ github.workspace }}
          ls -la
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "${{ github.workspace }}/artifact.tar.gz"
          target: "/home/ubuntu"
      - name: use the upload artifact github action
        uses: actions/upload-artifact@v3
        with:
          name: My artifact
          path: "${{ github.workspace }}/artifact.tar.gz"
      - name: executing remote ssh comands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/github/workspace
            tar -xczvf artifact.tar.gz
            ls -la
